# Generated by Django 4.2.4 on 2023-09-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='vk',
        ),
        migrations.AddField(
            model_name='customuser',
            name='insta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
    ]
