# Generated by Django 4.2.4 on 2023-09-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_video'),
        ('users', '0005_remove_customuser_vk_customuser_insta'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.location', verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
