# Generated by Django 4.2.4 on 2023-09-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_wishlist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус пользователя'),
        ),
    ]
