# Generated by Django 4.2.4 on 2023-09-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rebill_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rebill ID'),
        ),
    ]
