# Generated by Django 4.2.4 on 2023-09-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_rebill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_pay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписки'),
        ),
    ]
