# Generated by Django 4.2.4 on 2023-09-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, default='Free', max_length=100, null=True, verbose_name='Статус пользователя'),
        ),
    ]
