# Generated by Django 4.2.4 on 2023-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Хештеги',
                'verbose_name_plural': 'Хештеги',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('icon', models.ImageField(upload_to='icon/', verbose_name='Иконка')),
                ('addresses', models.CharField(max_length=200, verbose_name='Адрес')),
                ('latitude', models.CharField(max_length=250, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=250, verbose_name='Долгота')),
                ('hashtag', models.ManyToManyField(blank=True, null=True, to='index.hashtag', verbose_name='Хештеги')),
            ],
            options={
                'verbose_name': 'Локации',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
