# Generated by Django 4.2.4 on 2023-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
    ]
