# Generated by Django 4.2.4 on 2023-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='promo',
            field=models.CharField(default=1, max_length=250, verbose_name='Промокод'),
            preserve_default=False,
        ),
    ]
