# Generated by Django 4.2.4 on 2023-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_location_promo_alter_location_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='promo',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='location',
            name='subtitle',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Подзаголовок'),
        ),
    ]
