# Generated by Django 4.2.4 on 2023-10-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_location_promo_alter_location_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='promo_description',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='Описание промокода'),
        ),
    ]
