# Generated by Django 4.2.4 on 2023-10-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_location_promo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Город'),
        ),
    ]
