# Generated by Django 4.2.4 on 2023-10-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
