# Generated by Django 4.2.4 on 2023-10-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_people_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок')),
                ('percent', models.FloatField(verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
