# Generated by Django 4.2.4 on 2023-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_location_description_alter_location_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='Изображение'),
        ),
    ]
