# Generated by Django 4.2.5 on 2023-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_people_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='icon',
            field=models.ImageField(default=1, upload_to='icon/', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
